"""Collection must refuse an instrument the author has not read and signed.

WHY THIS FILE EXISTS
--------------------
`PLAN-2026-09-13-I3.md` Phase 1 gates on "the item-bank test passes, and A HUMAN HAS
READ ALL 60 ITEMS ONCE". `render_item_read.py` was written to make that read a ten-minute
job. It rendered `ITEM-READ-2026-09-15-i3-bank.md` with one checkbox per pair.

Every box stayed empty, and **372 sheets were collected against that bank anyway.**

Nothing read the checklist back. The renderer, the plan and the sheet all existed; the
only missing piece was something that fails when the boxes are blank. A gate that is a
document is not a gate — and the cost was a study that measured an instrument nobody had
approved while its author's own battery had zero records.

The tests below pin the CHECKER, not today's answer. The live instrument is expected to
be unapproved until the author signs it; a test asserting "the tree is currently clean"
would have to be disabled in the meantime, and a disabled gate is how this happened.
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "scripts"))

import check_instrument_approved as A  # noqa: E402

SHEET = """# The 4 items, for the read that gates collection

Generated by `scripts/render_item_read.py` from `bank.json`.

## P01 — topic
**One claim / specific / natural negation / critic side is the skeptical side?**  [x]

## P02 — topic
**One claim / specific / natural negation / critic side is the skeptical side?**  [x]
"""


def _bank(tmp_path, name="bank.json", pairs=2, status=None):
    items = []
    for p in range(pairs):
        a, b = 2 * p + 1, 2 * p + 2
        items += [{"id": a, "mirror_of": b, "frame": "critic", "text": "X %d." % p},
                  {"id": b, "mirror_of": a, "frame": "defender", "text": "Not X %d." % p}]
    doc = {"instrument": "test", "items": items}
    if status:
        doc["status"] = status
    path = tmp_path / name
    io.open(str(path), "w", encoding="utf-8").write(__import__("json").dumps(doc))
    return str(path)


def _sheet(tmp_path, text, name="ITEM-READ-test.md"):
    path = tmp_path / name
    io.open(str(path), "w", encoding="utf-8").write(text)
    return str(path)


def _with_study(tmp_path, monkeypatch):
    monkeypatch.setattr(A, "STUDY", str(tmp_path))


def test_a_signed_sheet_approves(tmp_path, monkeypatch):
    """Without this, every assertion below passes against a checker that always refuses."""
    _with_study(tmp_path, monkeypatch)
    bank = _bank(tmp_path)
    _sheet(tmp_path, SHEET)
    ok, findings = A.audit(bank)
    assert ok, findings


def test_an_unticked_sheet_refuses(tmp_path, monkeypatch):
    """THE REGRESSION: 32 empty boxes and 372 sheets collected against them."""
    _with_study(tmp_path, monkeypatch)
    bank = _bank(tmp_path)
    _sheet(tmp_path, SHEET.replace("[x]", "[ ]"))
    ok, findings = A.audit(bank)
    assert not ok
    assert any("UNTICKED" in f for f in findings), findings


def test_a_missing_sheet_refuses(tmp_path, monkeypatch):
    """No sheet at all is not the same as approval, and was treated as such."""
    _with_study(tmp_path, monkeypatch)
    ok, findings = A.audit(_bank(tmp_path))
    assert not ok
    assert any("NO SIGN-OFF SHEET" in f for f in findings), findings


def test_a_sheet_for_a_DIFFERENT_bank_does_not_approve_this_one(tmp_path, monkeypatch):
    """Matching is on the bank the sheet NAMES, not on the sheet's filename.

    A sheet called ITEM-READ-<the right date>-<the right words>.md that signs off some
    other file would otherwise pass by looking correct.
    """
    _with_study(tmp_path, monkeypatch)
    _bank(tmp_path, "ours.json")
    _sheet(tmp_path, SHEET)                      # names bank.json, not ours.json
    ok, findings = A.audit(str(tmp_path / "ours.json"))
    assert not ok
    assert any("NO SIGN-OFF SHEET" in f for f in findings), findings


def test_a_sheet_with_no_checkboxes_refuses(tmp_path, monkeypatch):
    """A sheet that cannot record a refusal cannot record an approval either."""
    _with_study(tmp_path, monkeypatch)
    bank = _bank(tmp_path)
    _sheet(tmp_path, "# read\n\nfrom `bank.json`\n\nlooks fine to me\n")
    ok, findings = A.audit(bank)
    assert not ok
    assert any("no checkboxes" in f for f in findings), findings


def test_fewer_ticks_than_pairs_refuses(tmp_path, monkeypatch):
    """Signing half an instrument is not signing it."""
    _with_study(tmp_path, monkeypatch)
    bank = _bank(tmp_path, pairs=4)
    _sheet(tmp_path, SHEET)                      # 2 ticks, 4 pairs
    ok, findings = A.audit(bank)
    assert not ok
    assert any("does not cover" in f for f in findings), findings


def test_a_withdrawn_bank_refuses_even_if_signed(tmp_path, monkeypatch):
    _with_study(tmp_path, monkeypatch)
    bank = _bank(tmp_path, status="WITHDRAWN 2026-09-16")
    _sheet(tmp_path, SHEET)
    ok, findings = A.audit(bank)
    assert not ok
    assert any("WITHDRAWN" in f for f in findings), findings


def test_an_absent_bank_is_not_applicable(tmp_path, monkeypatch):
    _with_study(tmp_path, monkeypatch)
    ok, _ = A.audit(str(tmp_path / "nope.json"))
    assert ok is None, "a missing bank is NOT APPLICABLE, not approved and not refused"


def test_the_collection_driver_calls_this_gate():
    """The check has to be wired in front of the spend, not merely available."""
    src = io.open(os.path.join(ROOT, "scripts", "run_i3_wave.py"), encoding="utf-8").read()
    assert "check_instrument_approved" in src, (
        "the wave driver does not consult the approval gate; it is a module nobody calls, "
        "which is exactly what render_item_read.py was")
    assert "REFUSING TO COLLECT -- the instrument is not approved." in src
