#!/usr/bin/env python3
"""bias-study-prep: end-to-end pre-study refresh.

Pulls relevant repos, rebuilds reference EPUBs, verifies toolchain health,
checks env vars, writes a dated prep-state.json file under the bias-study
runs/ directory.

Exit codes:
    0 = clean (study may proceed)
    1 = pre-flight blocker (study MUST NOT proceed)
"""
from __future__ import annotations

import collections
import datetime
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

WORKSPACE = Path(os.environ.get("BIAS_STUDY_WORKSPACE", Path.home()))
CLAUDE_TOOLS = Path(os.environ.get("CLAUDE_TOOLS", Path.home() / "claude"))

REPOS = {
    "publishing-tools": WORKSPACE / "publishing-tools",
    "books/evil-robots": WORKSPACE / "books" / "evil-robots",
    "books/the-ratchet": WORKSPACE / "books" / "the-ratchet",
    "evil-robots-series": WORKSPACE / "evil-robots-series",
    "fires-series": WORKSPACE / "fires-series",
    "G0DM0D3": CLAUDE_TOOLS / "G0DM0D3",
    "OBLITERATUS": CLAUDE_TOOLS / "OBLITERATUS",
}

def _resolve_study_dir():
    """The study tree this skill should operate on.

    THIS SHIPPED IN THE PUBLIC MIRROR POINTING AT A PRIVATE DIRECTORY. `WORKSPACE` defaulted to
    the home directory, so this resolved to an internal working-copy path that exists on exactly
    one machine. Anyone who cloned github.com/gorrie/bias-study and ran the skill shipped to ease
    reproduction got a subprocess traceback (`NotADirectoryError: [WinError 267]`), with nothing
    saying why.

    The mirror is itself a complete study tree: it has `scripts/`, `runs/` and `data/`. So the
    author's tree is used when it is there, and the repository this file lives in otherwise --
    which is the case that matters, because it is the only one a replicator has.
    """
    private = WORKSPACE / "evil-robots-series" / "research" / "bias-study"
    if (private / "scripts").is_dir():
        return private
    here = Path(__file__).resolve().parents[3]      # skills/<name>/scripts/ -> repo root
    if (here / "scripts").is_dir():
        return here
    raise SystemExit(
        "no study tree found. Looked for %s (the author's working copy) and %s (this "
        "repository). Set BIAS_STUDY_WORKSPACE if yours is elsewhere." % (private, here))


BIAS_STUDY_DIR = _resolve_study_dir()

# The JUDGE-SCORED battery's protocol files. Still checked, still present, and no longer the
# primary instrument: it was retired on 2026-08-29 in favour of a forced-choice bank. Kept
# because the v1/v2 data and every published claim resting on it are real -- but a green tick
# on these says nothing about a forced-choice run, which is how this skill came to pass
# vacuously in front of a collection it did not check.
LEGACY_PROTOCOL_FILES = [
    "README.md",
    "questions.md",
    "rubric.md",
    "schema.md",
    "run-protocol.md",
    "aggregation-rules.md",
]

# What a FORCED-CHOICE run actually depends on.
#
# THE INSTRUMENT CHANGED AND THIS LIST WAS THE LAST THING HOLDING THE OLD ONE UP.
# The study ran on 62 third-party propositions it could not republish: they forced
# an id-only data export, they caused the 2026-09-12 instrument leak, and the whole
# fingerprint / corpus-check apparatus exists to keep them out of the repository.
# They are gone.
#
# CORRECTED 2026-09-17. This constant then named a SECOND bank that was itself
# withdrawn: 60 items, generated by an assistant on 2026-09-14 and substituted for
# the author's instrument without his sentences ever being read. A pre-run gate
# naming a withdrawn bank as LIVE is the purest form of the defect this file's own
# comment describes -- it would have passed a collection against the wrong
# instrument and called it prepared.
#
# The live instrument is the author's own bank: `data/ratchet-battery.json`, 32
# items in 16 mirrored pairs, each pair a claim and its opposing framing written
# by hand. It ships in full under CC BY 4.0, so a replicator needs no fetch step
# and there is no leak surface.
#
# This mattered here more than anywhere else: `refresh.py` hard-coded "expected
# 62, 1..62" and made the whole prep verdict depend on it, so the first prep run
# after the instrument changed would have failed on the instrument being CORRECT.
# A pre-run gate that rejects the live instrument is worse than no gate: it
# teaches the operator to pass `--skip` and stop reading.
LIVE_INSTRUMENT = "data/ratchet-battery.json"

#: The retired one. Its presence is no longer required and no longer fatal; if it
#: is still on disk it is reported, because a fetched copy of licensed text
#: sitting in a tree that is about to be published is worth one line of output.
RETIRED_INSTRUMENT = "data/compass-propositions.json"

FORCED_CHOICE_FILES = [
    LIVE_INSTRUMENT,
    "scripts/run_compass.py",
    "scripts/test_compass_parser.py",
]

# Gates that must already pass BEFORE new runs land. If the paper disagrees with the data now,
# adding runs makes the disagreement harder to attribute rather than easier.
PRE_RUN_GATES = [
    ("gen_paper", ["scripts/gen_paper.py", "--check"]),
    ("key_numbers", ["scripts/key_numbers.py", "--check"]),
    ("controls_audit", ["scripts/controls_audit.py", "--strict"]),
    ("compass_parser", ["scripts/test_compass_parser.py"]),
    # Added 2026-09-02. Twenty-one scripts had diverged between the working study and the
    # public mirror, two of them at the statistics layer -- the private ci_analysis.py kept an
    # order-dependent bootstrap the mirror had already fixed. A rotted statistic looks exactly
    # like a statistic, so this is checked mechanically before a run rather than noticed later.
    ("no_fork", ["scripts/check_no_fork.py"]),
    # Added 2026-09-15, the day a wave was collected at a budget nobody had
    # measured against the roster.
    #
    # --max-tokens 4096 was taken from a Phase 2 smoke that was ONE model, and a
    # non-reasoning one. 372 sheets were launched on it; of the 231 that landed,
    # deepseek came back 95.8% invalid against openai's 7.7%, with 23 of 24
    # deepseek sheets sitting exactly at the cap. That is differential truncation
    # by verbosity -- this study's own FINDINGS #7 -- reproduced on its own
    # instrument, hours after the 800-token version of it had been repaired.
    #
    # The instruction existed. The plan's Phase 2 gate says the measured output
    # length sets the budget, and the design review attached a per-model probe to
    # it: "one model tells you nothing about the other seven ... set the token
    # budget from the LONGEST model's output, not the smoke model's." It was read
    # and not followed, because nothing in the execution path checked it.
    #
    # So it is checked here, where every study run passes. `probe_budget.py`
    # without --run reports coverage and exits 0 only when every model on the
    # frozen panel has been probed.
    ("budget_probe", ["scripts/probe_budget.py"]),
]

EPUB_BOOKS = ["books/evil-robots", "books/the-ratchet"]

REQUIRED_ENV = ["OPENROUTER_API_KEY"]
OPTIONAL_ENV = [
    "ANTHROPIC_API_KEY",
    "OPENAI_API_KEY",
    "GOOGLE_AI_API_KEY",
    "MISTRAL_API_KEY",
    "XAI_API_KEY",
    "DEEPSEEK_API_KEY",
    "HF_TOKEN",
]


def log(level: str, msg: str) -> None:
    print(f"[{level:5}] {msg}", flush=True)


def run(cmd: list[str], cwd: Path | None = None) -> tuple[int, str, str]:
    proc = subprocess.run(
        cmd,
        cwd=str(cwd) if cwd else None,
        capture_output=True,
        text=True,
    )
    return proc.returncode, proc.stdout.strip(), proc.stderr.strip()


def file_sha256(path: Path) -> str | None:
    if not path.exists():
        return None
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def git_pull_repo(name: str, path: Path) -> dict:
    result = {"name": name, "path": str(path)}
    if not (path / ".git").exists():
        result["status"] = "missing"
        log("ERROR", f"{name}: no git repo at {path}")
        return result

    rc, out, err = run(["git", "pull", "--ff-only"], cwd=path)
    if rc != 0:
        result["status"] = "pull-failed"
        result["error"] = err or out
        log("ERROR", f"{name}: git pull failed: {err or out}")
        return result

    rc, out, _ = run(["git", "rev-parse", "HEAD"], cwd=path)
    result["status"] = "ok"
    result["commit"] = out if rc == 0 else None
    log("OK   ", f"{name}: at {result['commit'][:12] if result['commit'] else '?'}")
    return result


def verify_protocol_dir() -> dict:
    result = {"path": str(BIAS_STUDY_DIR), "files": {}}
    if not BIAS_STUDY_DIR.exists():
        result["status"] = "missing"
        log("ERROR", f"protocol dir missing: {BIAS_STUDY_DIR}")
        return result

    all_ok = True
    for fn in LEGACY_PROTOCOL_FILES:
        fp = BIAS_STUDY_DIR / fn
        sha = file_sha256(fp)
        if sha is None:
            result["files"][fn] = {"status": "missing"}
            log("ERROR", f"protocol file missing: {fn}")
            all_ok = False
        else:
            size = fp.stat().st_size
            if size < 100:
                result["files"][fn] = {"status": "too-small", "size": size}
                log("ERROR", f"protocol file too small ({size}b): {fn}")
                all_ok = False
            else:
                result["files"][fn] = {"status": "ok", "sha256": sha, "size": size}
                log("OK   ", f"protocol: {fn} ({size}b)")

    result["status"] = "ok" if all_ok else "failed"
    return result


def verify_compass() -> dict:
    """The FORCED-CHOICE instrument: is it present, is it the right one, does the parser hold?

    Added 2026-09-02 after this skill was found scoped entirely to the retired battery. It
    checked six protocol files that still exist, passed, and said nothing about the instrument
    a collection was about to use.

    Rewritten 2026-09-15 for the instrument change. It asserted "expected 62, 1..62" against a
    third-party item set that has since been removed from the study, so the first prep run
    after the change would have FAILED ON THE INSTRUMENT BEING CORRECT. The invariants below
    are the ones the authored bank actually has, and they are stronger than a count: a mirrored
    pair whose halves do not differ by exactly one inserted "not" is not a mirror, and the
    frame gap measured on it is a different question wearing the same name.

    The name is kept so `prep-state` keys, the SKILL.md procedure and every existing test keep
    resolving; what it verifies is the live instrument.
    """
    result = {"files": {}, "status": "ok", "instrument": LIVE_INSTRUMENT}
    for rel in FORCED_CHOICE_FILES:
        fp = BIAS_STUDY_DIR / rel
        sha = file_sha256(fp)
        if sha is None:
            result["files"][rel] = {"status": "missing"}
            log("ERROR", f"forced-choice dependency missing: {rel}")
            result["status"] = "failed"
        else:
            result["files"][rel] = {"status": "ok", "sha256": sha}
            log("OK   ", f"forced-choice: {rel}")

    # The retired instrument is licensed text. Not required, not fatal, and worth
    # one line if a fetched copy is sitting in a tree that is about to be published.
    if (BIAS_STUDY_DIR / RETIRED_INSTRUMENT).exists():
        result["retired_instrument_present"] = True
        log("WARN ", f"retired third-party instrument still on disk: {RETIRED_INSTRUMENT} "
                     f"-- it is gitignored, and check_corpus is the gate that matters")

    items_path = BIAS_STUDY_DIR / LIVE_INSTRUMENT
    if not items_path.exists():
        return result
    try:
        payload = json.loads(items_path.read_text(encoding="utf-8"))
        items = payload["items"] if isinstance(payload, dict) and "items" in payload \
            else payload
        ids = sorted(int(i["id"]) for i in items)
        result["n_items"] = len(items)
        result["ids_contiguous"] = ids == list(range(1, len(items) + 1))
        if not result["ids_contiguous"]:
            log("ERROR", f"instrument ids are not contiguous 1..{len(items)}")
            result["status"] = "failed"

        # MIRRORED PAIRS, and the identity that makes them mirrors. Checked here
        # rather than trusted, because the generator that preceded this bank
        # DERIVED each negation and produced "have not more influence" and, on
        # the secrecy-orders item, a different proposition that collected and
        # scored cleanly. Identity is decidable; grammar is not.
        by_id = {int(i["id"]): i for i in items}
        pairs, seen, broken = [], set(), []
        for it in items:
            iid, mid = int(it["id"]), it.get("mirror_of")
            if iid in seen or mid is None:
                continue
            other = by_id.get(int(mid))
            if other is None:
                broken.append((iid, "mirror_of points nowhere"))
                continue
            seen.update({iid, int(mid)})
            a, b = (it.get("text") or "").split(), (other.get("text") or "").split()
            longer, shorter = (a, b) if len(a) >= len(b) else (b, a)
            if len(longer) - len(shorter) != 1:
                broken.append((iid, "halves differ by %d words" % (len(longer) - len(shorter))))
                continue
            removed = [w for w in longer if w not in shorter] or ["?"]
            rest = [w for w in longer if w != "not"]
            if removed[0] != "not" or rest != [w for w in shorter if w != "not"]:
                broken.append((iid, "the difference is not a single inserted 'not'"))
                continue
            pairs.append((iid, int(mid)))
        result["n_pairs"] = len(pairs)
        result["broken_pairs"] = broken
        if broken:
            result["status"] = "failed"
            log("ERROR", f"{len(broken)} pair(s) are not clean negations: {broken[:4]}")
        else:
            log("OK   ", f"instrument: {len(items)} items, {len(pairs)} mirrored pairs, "
                         f"every pair one inserted 'not'")

        # THE BANK DECLARES ITS OWN SIZE; check the file against its declaration
        # rather than against a number typed here. The previous version of this
        # function hard-coded "expected 62, 1..62", which is why it would have
        # rejected the replacement instrument for being the replacement
        # instrument. A constant in a pre-flight gate ages into a false alarm the
        # day the thing it describes legitimately changes -- and a false alarm in
        # a pre-run gate teaches the operator to skip it.
        #
        # Self-consistency still catches the case that matters: a bank that has
        # silently lost or gained a pair no longer matches the counts it ships.
        declared = payload.get("counts") if isinstance(payload, dict) else None
        if isinstance(declared, dict):
            want_items = declared.get("items")
            want_pairs = declared.get("pairs")
            result["declared_counts"] = {"items": want_items, "pairs": want_pairs}
            if want_items is not None and want_items != len(items):
                result["status"] = "failed"
                log("ERROR", f"instrument declares {want_items} items and holds {len(items)}")
            if want_pairs is not None and not broken and want_pairs != len(pairs):
                result["status"] = "failed"
                log("ERROR", f"instrument declares {want_pairs} pairs and holds {len(pairs)}")
        else:
            log("WARN ", "instrument declares no `counts` block; size is unchecked")

        # Frame balance. The acquiescence control is that the AFFIRMATIVE half is
        # the critic side on half the pairs and the defender side on the other
        # half, so a model that simply agrees more than it disagrees cannot
        # produce a frame gap. If that balance drifts, the gap is confounded.
        frames = collections.Counter((i.get("frame") or "?") for i in items)
        result["frames"] = dict(frames)
        if len(set(frames.values())) != 1:
            log("WARN ", f"frames are not balanced: {dict(frames)}")

        # One sentence per proposition -- a property the parser and the sheet
        # prompt both rely on.
        multi = [int(i["id"]) for i in items
                 if len(re.findall(r"[.!?](?=\s+[A-Z\"“]|$)",
                                   (i.get("text") or "").strip())) != 1]
        result["multi_sentence_items"] = multi
        if multi:
            log("WARN ", f"{len(multi)} proposition(s) are not exactly one sentence: "
                         f"{multi[:6]}")
    except (ValueError, KeyError, TypeError) as exc:
        result["status"] = "failed"
        log("ERROR", f"instrument unreadable: {exc}")
    return result


def run_pre_run_gates() -> dict:
    """Every gate must already pass before new runs land."""
    out = {"gates": {}, "status": "ok"}
    for name, argv in PRE_RUN_GATES:
        # A gate whose script is not in THIS tree is skipped, loudly, rather than failing the
        # run. Exactly one gate is in that position and it is there by design: check_no_fork.py
        # compares the public mirror against the private working study, so it can only run on
        # the side that can see both, and shipping it would name a private repository in a
        # public artifact. Before this, a clone of the public repo ran every gate, hit a
        # missing file, and ended on "FAILED -- bias study MUST NOT proceed", which reads as
        # "this study does not verify" when it means "you are not the maintainer".
        script = BIAS_STUDY_DIR / argv[0]
        if not script.exists():
            out["gates"][name] = {"exit": 0, "skipped": True,
                                  "last": f"{argv[0]} not present in this tree -- skipped"}
            log("SKIP ", f"gate {name}: {argv[0]} is not in this tree. This is expected on a "
                         f"clone of the public mirror; it is a maintainer-side check.")
            continue
        code, stdout, stderr = run([sys.executable] + argv, cwd=BIAS_STUDY_DIR)
        tail = (stdout or stderr or "").strip().splitlines()
        out["gates"][name] = {"exit": code, "last": tail[-1][:160] if tail else ""}
        if code == 0:
            log("OK   ", f"gate {name}: {out['gates'][name]['last']}")
        else:
            out["status"] = "failed"
            log("ERROR", f"gate {name} FAILED (exit {code}): "
                         f"{out['gates'][name]['last']}")
    return out


def snapshot_floors() -> dict:
    """Record every floor's pair count BEFORE the run.

    THIS IS THE CHECK THIS SKILL MOST NEEDED AND DID NOT HAVE. Twice -- 2026-09-01 with 27
    runs and 2026-09-02 with 14 -- runs were collected specifically to extend a floor and
    contributed NOTHING to it, because the floor tool carried a hardcoded list of run
    directories and a new directory is invisible to an include list by construction. Both
    times the collection looked successful and the row did not move.

    A pair count taken before the run turns that from something you notice later, if at all,
    into a subtraction. If the after-count equals the before-count, the runs did not land.
    """
    out = {"arms": {}, "status": "ok"}
    scripts_dir = BIAS_STUDY_DIR / "scripts"
    sys.path.insert(0, str(scripts_dir))
    try:
        import floor_table  # noqa: PLC0415
    except Exception as exc:                                   # noqa: BLE001
        out["status"] = "unavailable"
        out["error"] = str(exc)[:200]
        log("WARN ", f"floor snapshot unavailable: {str(exc)[:120]}")
        return out
    try:
        for fn in (floor_table.floor_order, floor_table.floor_same_version,
                   floor_table.floor_quant, floor_table.floor_ablation,
                   floor_table.floor_conditions):
            row = fn()
            if row:
                out["arms"][row["name"]] = {"n_pairs": row.get("n"),
                                            "side": row.get("side")}
                log("OK   ", f"floor before run: {row['name']} = {row.get('n')} pairs")
        by_class = floor_table.floor_order_by_class()
        for name, row in by_class.items():
            out["arms"][name] = {"n_pairs": row.get("n"), "side": row.get("side")}
            log("OK   ", f"floor before run: {name} = {row.get('n')} pairs")
    except Exception as exc:                                   # noqa: BLE001
        out["status"] = "failed"
        out["error"] = str(exc)[:200]
        log("ERROR", f"floor snapshot failed: {str(exc)[:120]}")
    return out


def build_epub(book_path: str) -> dict:
    full = WORKSPACE / book_path
    result = {"book": book_path}
    if not full.exists():
        result["status"] = "missing"
        log("ERROR", f"book missing: {book_path}")
        return result

    # sys.executable first: the interpreter already running this IS a valid interpreter, and
    # falling back to a PATH lookup can pick a different one than the caller intended. The old
    # fallback was one machine's MSYS path, which on any other host is simply a missing file.
    python_exe = sys.executable or shutil.which("python3") or shutil.which("python")
    build_py = WORKSPACE / "publishing-tools" / "build.py"
    if not build_py.exists():
        result["status"] = "build-script-missing"
        log("ERROR", f"build.py not found at {build_py}")
        return result

    log("INFO ", f"building EPUB: {book_path} (this may take 1-3 minutes)")
    rc, out, err = run([python_exe, str(build_py), book_path], cwd=WORKSPACE)

    # build.py uses exit code 0 = READY, 1 = NEEDS FIX, 2 = FAILED
    if rc == 0:
        result["status"] = "ready"
        epub_path = full / "output" / f"{full.name}.epub"
        result["epub_sha256"] = file_sha256(epub_path)
        result["epub_size"] = epub_path.stat().st_size if epub_path.exists() else None
        log("OK   ", f"{book_path}: STATUS READY ({result.get('epub_size', 0)} bytes)")
    elif rc == 1:
        result["status"] = "needs-fix"
        result["build_output_tail"] = out[-500:] if out else ""
        log("ERROR", f"{book_path}: STATUS NEEDS FIX (rc={rc})")
    else:
        result["status"] = "failed"
        result["build_output_tail"] = out[-500:] if out else ""
        result["build_error_tail"] = err[-500:] if err else ""
        log("ERROR", f"{book_path}: STATUS FAILED (rc={rc})")

    return result


def verify_toolchain(g0_path: Path, obl_path: Path) -> dict:
    """Verify G0DM0D3 + OBLITERATUS health. Lightweight — checks for presence
    of expected directories / config files, not deep dependency resolution.
    """
    result = {"g0dm0d3": {}, "obliteratus": {}}

    if g0_path.exists() and (g0_path / ".git").exists():
        result["g0dm0d3"]["present"] = True
        # Look for SOMETHING that signals the repo is intact
        markers = ["README.md", "package.json", "pyproject.toml", "requirements.txt"]
        result["g0dm0d3"]["markers_present"] = [m for m in markers if (g0_path / m).exists()]
        log("OK   ", f"G0DM0D3 present at {g0_path}, markers: {result['g0dm0d3']['markers_present']}")
    else:
        result["g0dm0d3"]["present"] = False
        log("ERROR", f"G0DM0D3 not found at {g0_path}")

    if obl_path.exists() and (obl_path / ".git").exists():
        result["obliteratus"]["present"] = True
        markers = ["README.md", "requirements.txt", "pyproject.toml", "setup.py"]
        result["obliteratus"]["markers_present"] = [m for m in markers if (obl_path / m).exists()]
        log("OK   ", f"OBLITERATUS present at {obl_path}, markers: {result['obliteratus']['markers_present']}")
    else:
        result["obliteratus"]["present"] = False
        log("ERROR", f"OBLITERATUS not found at {obl_path}")

    return result


def verify_env() -> dict:
    result = {"required": {}, "optional": {}}
    all_required_ok = True

    for var in REQUIRED_ENV:
        present = bool(os.environ.get(var))
        result["required"][var] = present
        if present:
            log("OK   ", f"env: {var} present")
        else:
            log("ERROR", f"env: {var} MISSING (required)")
            all_required_ok = False

    for var in OPTIONAL_ENV:
        present = bool(os.environ.get(var))
        result["optional"][var] = present
        if present:
            log("OK   ", f"env: {var} present (optional)")

    result["all_required_ok"] = all_required_ok
    return result


def write_prep_state(state: dict, run_dir: Path) -> Path:
    run_dir.mkdir(parents=True, exist_ok=True)
    out_path = run_dir / "prep-state.json"
    with out_path.open("w", encoding="utf-8") as f:
        json.dump(state, f, indent=2, sort_keys=True)
    return out_path


def main() -> int:
    started = datetime.datetime.utcnow().isoformat() + "Z"
    today = datetime.date.today().isoformat()
    run_dir = BIAS_STUDY_DIR / "runs" / today

    log("INFO ", f"bias-study-prep starting at {started}")
    log("INFO ", f"target run dir: {run_dir}")

    state = {
        "skill_version": "1.1.0",
        "started_at": started,
        "target_run_date": today,
        "repos": {},
        "protocol": {},
        "epubs": {},
        "toolchain": {},
        "env": {},
        "compass": {},
        "gates": {},
        "floors_before": {},
    }

    # 1. Git pulls
    log("INFO ", "=== Step 1: git pull ===")
    for name, path in REPOS.items():
        state["repos"][name] = git_pull_repo(name, path)

    repos_ok = all(r.get("status") == "ok" for r in state["repos"].values())

    # 2. Protocol dir check
    log("INFO ", "=== Step 2: protocol directory ===")
    state["protocol"] = verify_protocol_dir()

    # 3. EPUB rebuild
    log("INFO ", "=== Step 3: reference EPUB rebuild ===")
    for book in EPUB_BOOKS:
        state["epubs"][book] = build_epub(book)

    epubs_ok = all(b.get("status") == "ready" for b in state["epubs"].values())

    # 4. Toolchain health
    log("INFO ", "=== Step 4: G0DM0D3 + OBLITERATUS ===")
    state["toolchain"] = verify_toolchain(REPOS["G0DM0D3"], REPOS["OBLITERATUS"])

    toolchain_ok = (
        state["toolchain"]["g0dm0d3"].get("present", False)
        and state["toolchain"]["obliteratus"].get("present", False)
    )

    # 5. Env vars
    log("INFO ", "=== Step 5: env vars ===")
    state["env"] = verify_env()

    # 6. The FORCED-CHOICE instrument -- the one a run now actually uses.
    log("INFO ", "=== Step 6: forced-choice instrument ===")
    state["compass"] = verify_compass()

    # 7. Gates must already pass before new runs land.
    log("INFO ", "=== Step 7: pre-run gates ===")
    state["gates"] = run_pre_run_gates()

    # 8. Floor pair counts BEFORE the run, so a collection that lands nowhere is a
    #    subtraction rather than something nobody notices. See snapshot_floors.
    log("INFO ", "=== Step 8: floor snapshot ===")
    state["floors_before"] = snapshot_floors()

    # 9. Verdict
    state["completed_at"] = datetime.datetime.utcnow().isoformat() + "Z"
    compass_ok = state["compass"]["status"] == "ok"
    gates_ok = state["gates"]["status"] == "ok"
    all_ok = (
        repos_ok
        and state["protocol"]["status"] == "ok"
        and epubs_ok
        and toolchain_ok
        and state["env"]["all_required_ok"]
        and compass_ok
        and gates_ok
    )
    state["status"] = "ready" if all_ok else "failed"

    out_path = write_prep_state(state, run_dir)
    log("INFO ", f"prep-state written to {out_path}")

    if all_ok:
        log("OK   ", "=== READY — bias study may proceed ===")
        return 0
    else:
        log("ERROR", "=== FAILED — bias study MUST NOT proceed; fix and re-run ===")
        return 1


if __name__ == "__main__":
    sys.exit(main())
