#!/usr/bin/env python3
"""Generate PROTOCOL-DEVIATIONS.md: what was pre-registered, what was done, what changed.

WHY THIS EXISTS
---------------
This study scores twelve papers on whether their design decisions are recoverable, and
`OUTREACH-2026-09-13-author-letters.md` is built on the position that a reader should be able
to tell what was planned from what was done. Our own record of that is scattered across three
pre-registrations, three roster amendments inside `data/wave-panel.json`, a declared-losses
file, and a plan log -- so a reader has to assemble it, which is precisely the complaint.

Generated rather than written, from the machine-readable sources, so it cannot drift from
them. Every row names where it came from.

    python scripts/gen_deviations.py            # write the document
    python scripts/gen_deviations.py --check    # exit 1 if it is stale

Exit 0 current, 1 stale or rewritten.
"""
from __future__ import annotations

import argparse
import glob
import io
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import studypaths as _SP

TARGET = os.path.join(_SP.STUDY_DIR, "PROTOCOL-DEVIATIONS.md")
PANEL = os.path.join(_SP.STUDY_DIR, "data", "wave-panel.json")
LIMITS = os.path.join(_SP.STUDY_DIR, "data", "collection-limitations.json")

#: Amendment blocks in wave-panel.json, as (declared-key, criterion-key, list-key, label).
AMENDMENTS = [
    ("frozen", "criterion", "models", "the frozen panel"),
    ("amended", "amendment_criterion", "same_version_pairs", "same-version sibling coverage"),
    ("requant_siblings_declared", "requant_siblings_criterion", "requant_siblings",
     "requantisation null coverage"),
    ("breadth_declared", "breadth_criterion", "breadth", "panel breadth coverage"),
]


def load(path):
    with io.open(path, encoding="utf-8") as fh:
        return json.load(fh)


def preregs():
    """Every pre-registration, wherever this tree keeps them.

    THE STUDY KEEPS THEM AT THE ROOT; THE PUBLIC MIRROR KEEPS THEM IN `prereg/`. This globbed
    the root only, so run in the mirror it found none and regenerated PROTOCOL-DEVIATIONS.md
    with the entire pre-registration index missing -- thirteen rows, including
    `PREREG-2026-09-14-i3-phase4.md`, the main forced-choice collection every published figure
    comes from. It reported "wrote PROTOCOL-DEVIATIONS.md (183 lines)" and exited 0, and the
    document is the record a reader checks the paper against. Caught 2026-09-22 by reading the
    diff rather than the exit code.
    """
    roots = [_SP.STUDY_DIR, os.path.join(_SP.STUDY_DIR, "prereg")]
    paths = sorted({p for r in roots for p in glob.glob(os.path.join(r, "PREREG-*.md"))},
                   key=os.path.basename)
    # A DEVIATIONS RECORD WITH NO PRE-REGISTRATIONS IN IT IS NOT A DEVIATIONS RECORD. Every
    # tree that carries this generator carries preregs, so zero means the resolver missed them
    # -- which is exactly what happened -- and writing the file anyway publishes the absence as
    # a fact.
    if not paths:
        raise SystemExit(
            "NO PRE-REGISTRATIONS FOUND under %s. This generator will not write a deviations "
            "record with an empty pre-registration index: every tree that ships it has them, "
            "so zero means they are somewhere this function does not look."
            % " or ".join(os.path.relpath(r, _SP.STUDY_DIR) or "." for r in roots))
    out = []
    for path in paths:
        name = os.path.basename(path)
        head = ""
        with io.open(path, encoding="utf-8", errors="replace") as fh:
            for line in fh:
                if line.startswith("# "):
                    head = line[2:].strip()
                    break
        m = re.search(r"(\d{4}-\d{2}-\d{2})", name)
        out.append((m.group(1) if m else "", name, head))
    return out


def render():
    panel = load(PANEL) if os.path.exists(PANEL) else {}
    limits = load(LIMITS) if os.path.exists(LIMITS) else {}
    L = []
    A = L.append
    A("# Protocol deviations and amendments")
    A("")
    A("**Generated by `scripts/gen_deviations.py` from `data/wave-panel.json`,")
    A("`data/collection-limitations.json` and the `PREREG-*.md` files. Do not hand-edit --")
    A("`--check` exits 1 when this file disagrees with them.**")
    A("")
    A("This study scores other papers on whether a reader can tell what was planned from")
    A("what was done. This is that record for this study, in one place.")
    A("")
    A("## Pre-registrations")
    A("")
    A("| registered | document | governs |")
    A("|---|---|---|")
    for date, name, head in preregs():
        A("| %s | `%s` | %s |" % (date or "—", name, head or "—"))
    A("")
    A("## Roster amendments")
    A("")
    A("Every change to who is measured, with the rule that selected them. The standing")
    A("constraint is that selection is by COVERAGE and never by outcome: no model is added or")
    A("removed after seeing how it answered.")
    A("")
    for declared_key, crit_key, list_key, label in AMENDMENTS:
        declared = panel.get(declared_key)
        crit = panel.get(crit_key)
        members = panel.get(list_key)
        if not declared and not crit:
            continue
        A("### %s — declared %s" % (label, declared or "date not recorded"))
        A("")
        if crit:
            A("> %s" % crit.replace("\n", " "))
            A("")
        if isinstance(members, list):
            A("%d entries." % len(members))
            if members and isinstance(members[0], str):
                A("")
                A("```")
                for m in members:
                    A(m)
                A("```")
            A("")
    # A FROZEN PARAMETER THAT WAS OVERRIDDEN IS A DEVIATION, and this document had no way to
    # say so. `params.max_tokens` read 8192 while NOT ONE of the wave's 3,897 records was
    # collected at it -- the collector refused the frozen value as unsafe and the cap was
    # raised mid-collection, correctly. `wave.py --verify` therefore reported 100% of the
    # primary corpus as parameter drift, which reads as noise and gets ignored. The override
    # is recorded in `wave-panel.json` and rendered here, because a deviation kept only in a
    # data file is a deviation no reader of the deviations document ever sees.
    override = panel.get("params_overridden")
    frozen_params = panel.get("params_frozen_2026_09_05")
    seed_note = panel.get("seed_base_note")
    if override or seed_note:
        A("### collection parameters — where the frozen spec was overridden")
        A("")
        if override:
            A("> %s" % override.replace("\n", " "))
            A("")
        if frozen_params and panel.get("params"):
            A("| parameter | frozen | collected |")
            A("|---|---|---|")
            for key in sorted(set(frozen_params) | set(panel["params"])):
                was, now = frozen_params.get(key), panel["params"].get(key)
                if was != now:
                    A("| `%s` | %r | **%r** |" % (key, was, now))
            A("")
        if seed_note:
            A("> %s" % seed_note.replace("\n", " "))
            A("")
    rejected = panel.get("breadth_rejected") or {}
    if rejected:
        A("#### Rejected by the breadth rule, with the reason")
        A("")
        A("Recorded because a selection rule that only lists what it kept is not auditable.")
        A("")
        A("| listing | reason |")
        A("|---|---|")
        for model in sorted(rejected):
            A("| `%s` | %s |" % (model, rejected[model]))
        A("")

    A("## Declared collection losses")
    A("")
    models = limits.get("models") or []
    if models:
        A("Models whose own output is unusable on some sheets. Declared rather than dropped:")
        A("the pre-registration forbids removing a model from the roster after collection, so")
        A("these stay in every denominator and the loss is reported.")
        A("")
        A("| model | lost / attempted | separability | shape |")
        A("|---|---:|---|---|")
        for m in models:
            A("| `%s` | %s / %s | %s | %s |"
              % (m.get("model"), m.get("lost"), m.get("attempted"),
                 m.get("separability") or "—",
                 (m.get("shape") or "").split(".")[0][:110]))
        A("")
    blocking = limits.get("not_declared_and_still_blocking") or []
    if blocking:
        A("Still blocking acceptance, deliberately — infrastructure failures are")
        A("re-collectable and may not be declared away:")
        A("")
        for b in blocking:
            A("- `%s` — %s of %s sheets, `%s`. %s"
              % (b.get("model"), b.get("lost"), b.get("attempted"), b.get("shape"),
                 b.get("why_not_declared", "")))
        A("")
    resolved = limits.get("_RESOLVED")
    if resolved:
        A("### Resolved")
        A("")
        A("> %s" % resolved.replace("\n", " "))
        A("")
    A("## Where the remaining record lives")
    A("")
    A("- `CORRECTIONS-*.md` — every withdrawn or corrected claim, kept rather than deleted.")
    A("- `PLAN.md` §Log — dated record of what changed and why.")
    A("- `scripts/null_audit.py` — the minimum detectable effect behind every null reported.")
    A("- `RESULTS-*.md`, `FINDINGS-*.md` — results, with superseded text retained in place.")
    return "\n".join(L) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args(argv)
    want = render()
    have = ""
    if os.path.exists(TARGET):
        with io.open(TARGET, encoding="utf-8") as fh:
            have = fh.read()
    if a.check:
        if have.replace("\r\n", "\n").strip() != want.replace("\r\n", "\n").strip():
            print("PROTOCOL-DEVIATIONS.md is STALE -- run: python scripts/gen_deviations.py")
            return 1
        print("PROTOCOL-DEVIATIONS.md matches its sources.")
        return 0
    with io.open(TARGET, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(want)
    print("wrote %s (%d lines)" % (os.path.basename(TARGET), want.count("\n")))
    return 0


if __name__ == "__main__":
    sys.exit(main())
