#!/usr/bin/env python3
"""One machine-readable index per corpus root: what each run is, and what may be concluded.

WHY THIS EXISTS
---------------
`data/2026-09-13-i3-phase0/` ships in the public release. 3,200 records. The records carry no
`instrument` field and no status; the `manifest.json` beside them reads as a clean success --
1,600 calls completed, 0 failed. **The B-A contrast computed on that arm is withdrawn**: the
baseline instructs "do not take a personal position", the rubric scores 3 as "does not commit",
condition A returns exactly 3 on 100% of records for three of four models, so every B-A is
arithmetically B-3 -- instruction-following, not a lean. A content-free placebo reproduces 78%
of grok-4.3's effect.

Nothing on disk said any of that. A reader could download the release, find a healthy-looking
run directory, compute the contrast and publish a number this study has withdrawn, without
doing a single thing wrong.

`data/withdrawals.json` governs claims on OUR surfaces -- `check_withdrawals.py` fails when a
withdrawn wording appears in the paper, the README or the website. It never reached the
records. This closes that gap from the other end: every corpus root gets a `PROVENANCE.json`
naming every run in it, the instrument its records carry, whether it belongs to the current
study or to previous work, and whether a conclusion drawn from it has been withdrawn.

It is GENERATED. The status is read from the withdrawals registry through
`derive_manifest._withdrawal_for`, so there is still exactly one record of a withdrawal and
everything else derives from it -- and that lookup matches on path SEGMENTS, because a
substring match once labelled the paper's entire corpus withdrawn on the strength of an
archived snapshot path that merely contained the run's name.

    python scripts/gen_provenance.py            # print, write nothing
    python scripts/gen_provenance.py --write
    python scripts/gen_provenance.py --check    # exit 1 if any root's index is stale

Exit 0 current, 1 stale or a defect, 2 NOT APPLICABLE (no corpus root here).
"""
from __future__ import annotations

import argparse
import datetime as dt
import io
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
STUDY = os.path.dirname(HERE)
sys.path.insert(0, HERE)

import run_inventory as RI  # noqa: E402

INDEX = "PROVENANCE.json"

#: Said in the file itself, because the reader who most needs it is the one who will not read
#: our prose. Kept short enough to survive being skimmed.
PREAMBLE = (
    "Generated by scripts/gen_provenance.py. One entry per run directory in this root. "
    "`status` is read from data/withdrawals.json: `withdrawn` means a conclusion drawn from "
    "that run has been withdrawn by the study that collected it -- the records are published "
    "so the withdrawal is checkable, NOT so the claim can be recomputed. `corpus` is `current` "
    "when every record carries the live instrument and `previous` otherwise; a `MIXED` run "
    "would be a defect, since no figure can be computed across two instruments."
)


def build():
    """root name -> index dict. One pass of the inventory, split by the root it lives in."""
    # CLASSIFY, do not just scan. `scan()` returns rows without `role`; the first version
    # shipped `"role": null` for all 70 runs, which is a field that looks answered and is not.
    rows = RI.classify(RI.scan(STUDY), RI.documented(STUDY))
    # WHICH documents, not just whether one exists. The pre-registration and the results
    # document of a run are what a reader needs next, and until 2026-09-25 the index only
    # said "named in a document" and left the search to them.
    naming = RI.documents_naming(STUDY)
    by_root: dict[str, list] = {}
    for root in RI._corpus_roots(STUDY):
        name = os.path.basename(root.rstrip(os.sep)) or root
        by_root[name] = []
    for r in rows:
        for root in RI._corpus_roots(STUDY):
            name = os.path.basename(root.rstrip(os.sep)) or root
            if os.path.isdir(os.path.join(root, r["run"])):
                by_root[name].append(r)
                break
    out = {}
    for name, group in by_root.items():
        runs = {}
        for r in sorted(group, key=lambda x: x["run"]):
            entry = {
                "records": r["records"],
                "models": r["models"],
                "conditions": r["conditions"],
                "instrument": r.get("instruments") or {},
                "corpus": r.get("corpus"),
                "status": r.get("status"),
                "role": r.get("role"),
                "why": r.get("why"),
                "documents": naming.get(r["run"], []),
            }
            if r.get("status") == "withdrawn":
                import derive_manifest
                w = derive_manifest._withdrawal_for(r["run"]) or {}
                entry["withdrawn"] = {
                    "claim": w.get("claim"),
                    "date": w.get("withdrawn"),
                    "record": w.get("record"),
                    "note": w.get("note"),
                }
            runs[r["run"]] = entry
        out[name] = {
            "READ_THIS_FIRST": PREAMBLE,
            "root": name,
            "generated_by": "scripts/gen_provenance.py",
            "runs_total": len(runs),
            "records_total": sum(r["records"] for r in group),
            "by_corpus": _tally(group, "corpus"),
            "by_status": _tally(group, "status"),
            "runs": runs,
        }
    return out


def _tally(group, field):
    out: dict[str, int] = {}
    for r in group:
        out[str(r.get(field))] = out.get(str(r.get(field)), 0) + 1
    return dict(sorted(out.items()))


def _render(doc):
    # `generated_at` is deliberately NOT in the document. A timestamp makes every regeneration
    # a diff, which makes `--check` useless as a staleness signal and trains a reader to ignore
    # it -- the same reason the corpus fingerprint carries none.
    return json.dumps(doc, indent=1, ensure_ascii=False, sort_keys=False) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)

    roots = RI._corpus_roots(STUDY)
    if not roots:
        print("NOT APPLICABLE: no corpus root under %s" % STUDY)
        return 2

    docs = build()
    if not docs:
        # A GENERATOR THAT FOUND NOTHING MUST NOT WRITE AN EMPTY INDEX AND EXIT 0.
        print("gen_provenance: no corpus root produced an index; nothing was described.")
        return 1

    stale, wrote = [], []
    for name, doc in docs.items():
        path = os.path.join(STUDY, name, INDEX)
        want = _render(doc)
        have = io.open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if args.write:
            io.open(path, "w", encoding="utf-8", newline="\n").write(want)
            wrote.append(name)
        elif have != want:
            stale.append(name)
        if not args.check and not args.write:
            print("%s/  %d run(s), %d record(s)  %s"
                  % (name, doc["runs_total"], doc["records_total"], doc["by_status"]))

    if args.write:
        for name in wrote:
            print("wrote %s/%s  (%d runs)" % (name, INDEX, docs[name]["runs_total"]))
        return 0
    if args.check:
        if stale:
            print("STALE -- %d root index(es) disagree with the corpus: %s"
                  % (len(stale), ", ".join(stale)))
            print("Run: python scripts/gen_provenance.py --write")
            return 1
        print("provenance: %d root index(es) match the corpus (%d runs described)"
              % (len(docs), sum(d["runs_total"] for d in docs.values())))
    return 0


if __name__ == "__main__":
    sys.exit(main())
