#!/usr/bin/env python3
"""Render the paper's reference list from data/controls-audit.json.

A bibliography maintained separately from the audit is two copies of the same fact, and this
project has already watched what that produces: our note said Kamal was ACL 2025 (it is
IJCNLP-AACL 2025, a short paper), and said "Cen" without an author list, a year, or a venue,
for a citation we were about to build a contradiction on.

So the citation and the verdict come out of one record. If a study is in the audit it is in the
references, with the provenance stamp attached, because a reader is entitled to know whether a
claim about a paper came from reading it or from remembering it.

    python scripts/references.py             # markdown reference list
    python scripts/references.py --bibtex    # bibtex keys matching the audit ids
"""
from __future__ import annotations

import argparse
import io
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
STUDY = os.path.dirname(HERE)
DATA = os.path.join(STUDY, "data", "controls-audit.json")

PROV = {
    "full-text": "read in full",
    "retrieved-summary": "abstract and method retrieved; full text not read",
    "project-review": "FROM OUR OWN NOTES, NOT RE-VERIFIED",
}


def _closed(text):
    """End a reference field with a full stop unless it already ends a sentence."""
    text = text.rstrip()
    return text if text.endswith((".", "?", "!")) else text + "."


def load():
    with io.open(DATA, encoding="utf-8") as fh:
        return json.load(fh)


def sortkey(s):
    return (s["id"] == "ours", s["id"] == "aipolcom", s["cite"].split(",")[0].lower())


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--bibtex", action="store_true")
    args = ap.parse_args(argv)

    doc = load()
    studies = sorted(doc["studies"], key=sortkey)

    if args.bibtex:
        for s in studies:
            if s["id"] == "ours":
                continue
            year = s["year"]
            first = re.split(r"[ ,]", s["cite"].strip())[0]
            print("@misc{%s," % s["id"])
            print("  note = {%s}," % s["cite"].replace("{", "").replace("}", ""))
            print("  year = {%d}," % year)
            print("  author = {%s et al.}," % first)
            print("}")
        return 0

    print("## References\n")
    print("Generated by `scripts/references.py` from `data/controls-audit.json`, the same "
          "record that supplies each study's row in the controls table. The provenance note "
          "on each entry says how we know what we claim about it.\n")
    for s in studies:
        if s["id"] == "ours":
            continue
        # Every field closes as a sentence: run together unpunctuated, "arXiv:2601.06194v1
        # Instrument: ..." read as one clause in the typeset paper.
        print("- **%s** — %s" % (s["id"], _closed(s["cite"])))
        detail = []
        if s.get("instrument"):
            detail.append("*Instrument:* %s" % _closed(s["instrument"]))
        if s.get("scale"):
            detail.append("*Scale:* %s" % _closed(s["scale"]))
        if detail:
            print("  %s" % "  ".join(detail))
        print("  *Provenance:* %s." % PROV.get(s["provenance"], s["provenance"]))
    print()
    # THE READ-IN-FULL COUNT, COUNTED. Not "all of them", which is what this block used to
    # say -- "All studies in the audit have been read in full or retrieved directly" folds
    # `full-text` and `partial` into one clause and reads as the stronger claim. The document
    # previously carried a hand-typed "All twelve are now read in full", and `sclar2024` has
    # always been provenance `partial` with a note saying the full text was not read end to
    # end. That contradiction is the first entry in this very file. Restating it through a
    # generator would be the same error with a build step.
    external = [s for s in studies if s["id"] != "ours"]
    full = [s["id"] for s in external if s["provenance"] == "full-text"]
    unread = [s["id"] for s in external if s["provenance"] == "project-review"]
    partial = [s["id"] for s in external if s["provenance"] == "partial"]
    n = len(external)
    WORD = {11: "Eleven", 12: "Twelve", 10: "Ten", 13: "Thirteen", 14: "Fourteen"}
    print("%s of the %s are read in full. %s"
          % (WORD.get(len(full), str(len(full))),
             {12: "twelve", 11: "eleven", 13: "thirteen"}.get(n, "%d" % n),
             ("The remainder — %s — %s consulted as abstract and PDF without the full text "
              "being read end to end, and no verdict in the controls table rests on more "
              "than that."
              % (", ".join(sorted(partial)), "was" if len(partial) == 1 else "were"))
             if partial else
             "No verdict in the controls table rests on a second-hand note."))
    if unread:
        print()
        print("**%d record(s) still unread: %s.** No claim about what these studies did or "
              "did not do may appear in the paper until they are read."
              % (len(unread), ", ".join(sorted(unread))))
    return 0


if __name__ == "__main__":
    sys.exit(main())
