#!/usr/bin/env python3
"""Render the paper's reference list from data/controls-audit.json.

A bibliography maintained separately from the audit is two copies of the same fact, and this
project has already watched what that produces: our note said Kamal was ACL 2025 (it is
IJCNLP-AACL 2025, a short paper), and said "Cen" without an author list, a year, or a venue,
for a citation we were about to build a contradiction on.

So the citation and the verdict come out of one record. If a study is in the audit it is in the
references, with the provenance stamp attached, because a reader is entitled to know whether a
claim about a paper came from reading it or from remembering it.

    python scripts/references.py             # markdown reference list
    python scripts/references.py --bibtex    # bibtex keys matching the audit ids
"""
from __future__ import annotations

import argparse
import io
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
STUDY = os.path.dirname(HERE)
DATA = os.path.join(STUDY, "data", "controls-audit.json")

PROV = {
    "full-text": "read in full",
    "retrieved-summary": "abstract and method retrieved; full text not read",
    "project-review": "FROM OUR OWN NOTES, NOT RE-VERIFIED",
}


def load():
    with io.open(DATA, encoding="utf-8") as fh:
        return json.load(fh)


def sortkey(s):
    return (s["id"] == "ours", s["id"] == "aipolcom", s["cite"].split(",")[0].lower())


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--bibtex", action="store_true")
    args = ap.parse_args(argv)

    doc = load()
    studies = sorted(doc["studies"], key=sortkey)

    if args.bibtex:
        for s in studies:
            if s["id"] == "ours":
                continue
            year = s["year"]
            first = re.split(r"[ ,]", s["cite"].strip())[0]
            print("@misc{%s," % s["id"])
            print("  note = {%s}," % s["cite"].replace("{", "").replace("}", ""))
            print("  year = {%d}," % year)
            print("  author = {%s et al.}," % first)
            print("}")
        return 0

    print("## References\n")
    print("Generated by `scripts/references.py` from `data/controls-audit.json`, the same "
          "record that supplies each study's row in the controls table. The provenance note "
          "on each entry says how we know what we claim about it.\n")
    for s in studies:
        if s["id"] == "ours":
            continue
        print("- **%s** — %s" % (s["id"], s["cite"]))
        detail = []
        if s.get("instrument"):
            detail.append("*Instrument:* %s" % s["instrument"])
        if s.get("scale"):
            detail.append("*Scale:* %s" % s["scale"])
        if detail:
            print("  %s" % "  ".join(detail))
        print("  *Provenance:* %s." % PROV.get(s["provenance"], s["provenance"]))
    print()
    unread = [s["id"] for s in studies if s["provenance"] == "project-review"]
    if unread:
        print("**%d record(s) still unread: %s.** No claim about what these studies did or "
              "did not do may appear in the paper until they are read."
              % (len(unread), ", ".join(unread)))
    else:
        print("All studies in the audit have been read in full or retrieved directly. No "
              "verdict in the controls table rests on a second-hand note.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
