#!/usr/bin/env python3
"""Render the I3 bank as 30 pairs for the human read that gates Phase 2.

`PLAN-2026-09-13-I3.md` Phase 1 gates on two things: the item-bank test passes,
and A HUMAN HAS READ ALL 60 ITEMS ONCE. The test passes. This exists so the read
is a ten-minute job rather than a JSON crawl, because a gate that is tedious to
clear is a gate that gets waved through -- and the last time these pairs were
read by a human, SIX OF TEN WERE BROKEN (`ITEM-AUDIT-2026-09-14-mirror-pairs.md`).

The reader applies ONE test, the fourth rule from that audit, which is the rule
all five failures broke:

    Can I agree with BOTH halves without contradicting myself?

If yes, the pair is not a mirror and the frame gap measured on it is a different
question, which reads exactly like frame-following. That is the error the
experiment exists to detect, so it cannot sit inside the instrument.

The machine already checks IDENTITY -- `verify_negation` asserts the two halves
are the same token sequence bar one inserted "not". It cannot check whether the
resulting proposition is one a person could coherently hold both ways, and that
is the whole of what the human is for. The diff is shown per pair so the reader
can see exactly what the machine checked and judge the part it could not.

    python scripts/render_item_read.py > ITEM-READ-<date>-i3-bank.md
"""
from __future__ import annotations

import difflib
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
STUDY = os.path.dirname(HERE)
#: Default: whichever bank the runner would administer. Hardcoding one meant the sheet
#: could only ever sign off that bank, so the study's own instrument had no way to be read.
def _default_bank():
    try:
        sys.path.insert(0, HERE)
        import run_compass
        return str(run_compass.ITEMS_PATH)
    except Exception:
        return os.path.join(STUDY, "data", "ratchet-battery.json")


BANK = _default_bank()


def diff_words(a: str, b: str) -> str:
    """The inserted/removed span between the halves, as words."""
    aw, bw = a.split(), b.split()
    out = []
    for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, aw, bw).get_opcodes():
        if tag == "equal":
            continue
        removed = " ".join(aw[i1:i2])
        added = " ".join(bw[j1:j2])
        if removed and added:
            out.append("%s -> %s" % (removed, added))
        elif added:
            out.append("+%s" % added)
        elif removed:
            out.append("-%s" % removed)
    return "; ".join(out) or "(no textual difference -- INVESTIGATE)"


def main(argv=None) -> int:
    import argparse
    ap = argparse.ArgumentParser(description=__doc__.split(chr(10))[0])
    ap.add_argument("--items", default=BANK, help="bank to render (default: the live instrument)")
    args = ap.parse_args(argv)
    with open(args.items, encoding="utf-8") as fh:
        bank = json.load(fh)
    items = bank["items"]
    by_id = {it["id"]: it for it in items}

    pairs, seen = [], set()
    for it in items:
        if it["id"] in seen:
            continue
        other = by_id.get(it.get("mirror_of"))
        if other is None:
            pairs.append((it, None))
            seen.add(it["id"])
            continue
        crit, inst = (it, other) if it.get("frame") == "critic" else (other, it)
        pairs.append((crit, inst))
        seen.update({it["id"], other["id"]})

    w = sys.stdout.write
    # AUTHOR-WRITTEN BANKS HAVE NO `generated_by`. Requiring one meant this could render a
    # sheet only for a bank a machine had built -- so the study's own instrument was the one
    # thing that could not be signed off, and the bank that could was the unapproved one.
    built = (", built by `%s`" % bank["generated_by"]) if bank.get("generated_by") \
        else " (author-written)"
    w("# The %d items, for the read that gates collection\n\n" % len(items))
    w("**Instrument:** `%s`, version %s, created %s%s.\n\n"
      % (bank.get("instrument", "?"), bank.get("version", "?"),
         bank.get("created", "?"), built))
    w("**Scale:** %s\n\n" % bank.get("position_scale", "?"))
    w("Generated by `scripts/render_item_read.py` from `%s`. "
      "Do not hand-edit; fix the bank and regenerate.\n\n" % os.path.basename(args.items))
    w("---\n\n")
    w("## What you are checking — and what you are NOT\n\n")
    # WHICH READ THIS IS depends on how the bank is built, and getting it wrong makes the
    # sheet tell the reader to skip the only check that matters.
    #
    # A literal-negation bank ("X" / "not X") cannot fail the complementarity rule, so its
    # sheet says don't spend the read there. An AUTHORED bank pairs two written propositions,
    # and complementarity is exactly what can fail -- five of v3's sixteen pairs admit
    # agreement with both halves. Rendering the literal-negation preamble over an authored
    # bank instructed the reader past the decisive question.
    literal = 0
    for crit, inst in pairs:
        if inst is not None:
            try:
                import build_item_bank as _B
                if _B.verify_negation(crit["text"], inst["text"]) is None:
                    literal += 1
            except Exception:                           # noqa: BLE001
                pass
    is_literal_bank = pairs and literal >= 0.8 * len([p for p in pairs if p[1] is not None])

    w("The gate is the fourth rule of `ITEM-AUDIT-2026-09-14-mirror-pairs.md`: *can a "
      "coherent person agree with both halves?* Five of ten Phase 0 pairs failed it.\n\n")
    if is_literal_bank:
        w("**That rule cannot fail in this bank, so do not spend the read on it.** Every pair "
          "below is a literal negation — the same sentence bar one inserted \"not\", asserted "
          "by `verify_negation` and shown on each `diff` line. Nobody can coherently agree "
          "with both *X* and *not X*.\n\n")
        w("A gate that cannot fail is a rubber stamp, so the read is aimed at what "
          "construction does **not** guarantee. Four things, per pair:\n\n")
    else:
        w("**THIS BANK IS AUTHORED, NOT DERIVED, so that rule is live and it is the main "
          "thing you are checking.** These pairs are two written propositions, not a sentence "
          "and its negation, so nothing mechanical has ruled out a pair a coherent person can "
          "agree with twice. Read each pair and ask the question directly:\n\n")
        w("> **Can I agree with BOTH halves without contradicting myself?**\n\n")
        w("If yes, the pair is not a mirror, and the frame gap measured on it is a different "
          "question — which reads exactly like frame-following, the error the experiment "
          "exists to detect. Tick only the pairs where the answer is no. Then four more, per "
          "pair:\n\n")
    w("1. **ONE claim, not two.** A double-barrelled proposition ('should require a licence "
      "and an audit') cannot be answered by someone who splits on it, and its negation is "
      "ambiguous. This is the most likely remaining defect.\n")
    w("2. **Specific enough that agreement means something.** If 'agree' could mean three "
      "different positions, the item measures which one the model picked, not where it "
      "stands.\n")
    w("3. **The negation is natural English.** The generator that preceded this bank produced "
      "'have not more influence' and 'has not leverage'. A reader who stumbles is a model that "
      "stumbles.\n")
    w("4. **The critic half is actually the institution-skeptical half.** This is the one with "
      "teeth: the frame gap is critic minus institution, paired. **A mislabelled frame flips "
      "the sign of the primary outcome on that pair**, and nothing mechanical can catch it "
      "because both labels are grammatical. Check the `critic` row is the side a critic of "
      "institutions would take.\n\n")
    w("Mark a pair **X** if it fails any of the four, **?** if unsure. Blank means good.\n\n")
    w("---\n\n")

    counts = bank.get("counts") or {}
    if counts:
        w("**Bank counts as built:** %s\n\n"
          % ", ".join("%s %s" % (k.replace("_", " "), v) for k, v in counts.items()))

    for crit, inst in pairs:
        pid = crit.get("pair_id") or "P??"
        w("## %s — %s\n\n" % (pid, crit.get("topic", "?")))
        if crit.get("pair_note"):
            w("*%s*\n\n" % crit["pair_note"])
        w("| | item | text |\n|---|---|---|\n")
        w("| critic | #%s (%s) | %s |\n"
          % (crit["id"], crit.get("polarity", "?"), crit["text"]))
        if inst is not None:
            w("| institution | #%s (%s) | %s |\n"
              % (inst["id"], inst.get("polarity", "?"), inst["text"]))
            w("\n`diff:` %s\n\n" % diff_words(crit["text"], inst["text"]))
        else:
            w("\n**UNPAIRED — no mirror_of. Investigate.**\n\n")
        w("**One claim / specific / natural negation / critic side is the skeptical side?**  [ ]\n\n")

    w("---\n\n")
    w("## Sign-off\n\n")
    w("%d pairs, %d items rendered.\n\n" % (len(pairs), len(items)))
    w("- [ ] I have read all %d items once.\n" % len(items))
    w("- [ ] Pairs marked X above are excluded from the frame-gap primary outcome.\n\n")
    w("Read by: ______________________  date: ____________\n\n")
    w("Phase 1's gate in `PLAN-2026-09-13-I3.md` is met when the box above is ticked. "
      "Nothing in Phase 2 collects until then.\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
